apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  labels:
    app: order-api
spec:
  # 가용성을 위해 서버 2개를 동시에 실행합니다.
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: loa-store/order-api:latest
        imagePullPolicy: Never # 로컬에서 빌드한 이미지를 사용하도록 설정
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service" # Redis 서비스와 이름으로 통신합니다.
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
spec:
  # 클러스터 내부에서 API 서버에 접근하기 위한 설정
  selector:
    app: order-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
